github.com:
    users:
        ROBatBOT:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: ROBatBOT
